title: Gamgoon's Note
name: Gamgoon's Note
url: https://gamgoon.github.io
description: keep learning...

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

theme: jekyll-theme-midnight